//
//  ForgotPresenter.swift
//  task1
//
//  Created Quan Tran on 7/2/17.
//  Copyright © 2017 Quan Tran. All rights reserved.
//
//  Template generated by Hao Nguyen
//

import UIKit

class ForgotPresenter: ForgotPresenterProtocol {

    weak private var view: ForgotViewProtocol?       //Giao tiếp với view
    private let interactor: ForgotInteractorProtocol //Giao tiếp với interactor
    private let router: ForgotWireframeProtocol      //Giao tiếp với router

    var presenter: ForgotPresenterProtocol?
    init(interface: ForgotViewProtocol, interactor: ForgotInteractorProtocol, router: ForgotWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router

        self.interactor.presenter = self
    }
    func getDataPass(userName: String, kindOfSecurity: String, isEmail: Bool) {
        interactor.inputDataPass(userName: userName, kindOfSecurity: kindOfSecurity, isEmail: isEmail)

    }
    func getDataUser(cmnd: String, birthday: String, kindOfSecurity: String, isEmail: Bool) {
        interactor.inputDataUser(cmnd: cmnd, birthday: birthday, kindOfSecurity: kindOfSecurity, isEmail: isEmail)
    }
    func respondDataPass(_ result: Bool) {
        view?.getRespondForPass(result: result)
        
    }

    

    func respondDataUser(_ result: Bool) {
        view?.getRespondForUser(result: result)        
    }

    func loadLogin() {
        router.loadLogin()
    }
}
 

