//
//  ForgotRouter.swift
//  task1
//
//  Created Quan Tran on 7/2/17.
//  Copyright © 2017 Quan Tran. All rights reserved.
//
//  Template generated by Hao Nguyen
//

import UIKit

class ForgotRouter: ForgotWireframeProtocol {
    
    weak var viewController: UIViewController?
    class var sharedInstance : ForgotRouter {
        struct Static {
            static let instance : ForgotRouter = ForgotRouter()
        }
        return Static.instance
    }

    static func createModule(_ window: UIWindow) {
        // Change to get view from storyboard if not using progammatic UI
        let view = ForgotViewController()
        let interactor = ForgotInteractor()
        let router = ForgotRouter()
        let presenter = ForgotPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        //setup view root
        self.sharedInstance.viewController = view
        let navController = UINavigationController.init(rootViewController: view)
        window.rootViewController = navController
    }
    func loadLogin() {
        viewController?.navigationController?.popViewController(animated: true)
        let view = ForgotViewController()
        viewController?.navigationController?.pushViewController(view, animated: true)

    }
}

























