//
//  ForgotProtocols.swift
//  task1
//
//  Created Quan Tran on 7/2/17.
//  Copyright © 2017 Quan Tran. All rights reserved.
//
//  Template generated by Hao Nguyen
//

import Foundation

//MARK: Wireframe -
protocol ForgotWireframeProtocol: class {
    func loadLogin()
}
//MARK: Presenter -
protocol ForgotPresenterProtocol: class {
    func getDataPass(userName :String , kindOfSecurity :String, isEmail :Bool)
    func getDataUser(cmnd:String, birthday:String, kindOfSecurity:String, isEmail:Bool)
    func respondDataPass(_ result: Bool)
    func respondDataUser(_ result: Bool)
    func loadLogin()
}

//MARK: Interactor -
protocol ForgotInteractorProtocol: class {

  var presenter: ForgotPresenterProtocol?  { get set }
    func inputDataPass(userName:String, kindOfSecurity:String, isEmail:Bool)
    func inputDataUser(cmnd:String, birthday:String, kindOfSecurity:String, isEmail:Bool)
}

//MARK: View - 
protocol ForgotViewProtocol: class {

  var presenter: ForgotPresenterProtocol?  { get set }
    func getRespondForUser(result: Bool)
    func getRespondForPass(result: Bool)
}
